# Generated by Django 5.0.3 on 2024-03-10 21:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('auto', 'Auto'), ('pickup', 'Pickup'), ('comercial', 'Comercial'), ('suv', 'SUV'), ('crossover', 'Cross Over')], max_length=100)),
                ('fecha_auto', models.DateField(verbose_name='Fecha del modelo')),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auto.ficha')),
            ],
        ),
    ]
