# Generated by Django 5.0.3 on 2024-03-11 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_rename_caracteristicas_caracteristica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_titulo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.ficha'),
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/ficha/caractericas'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='hero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.hero'),
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/ficha/prestaciones')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.ficha')),
            ],
        ),
    ]
