# Generated by Django 5.0.3 on 2024-03-11 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_hero_remove_ficha_descripcion_remove_ficha_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/ficha/hero'),
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='auto.ficha'),
        ),
        migrations.AlterField(
            model_name='prestacion',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestaciones', to='auto.ficha'),
        ),
    ]
