# Generated by Django 5.0.3 on 2024-03-11 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_hero_image_alter_caracteristica_ficha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='hero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ficha', to='auto.hero'),
        ),
    ]
